import { ROUTES, routeById } from '../data/routes/index.js';
import { ITEMS,itemById,BAG_LIMIT,HAND_LIMIT } from '../data/items.js';
import { CONTACTS,SOCIAL_PROMPT } from '../data/contacts.js';
import { ENDINGS,returnQuestions } from '../data/endings.js';
import * as E from './engine.js';
import { drawMap,scene,avatar } from './art.js';
const $=s=>document.querySelector(s),app=$('#app'),modal=$('#modal');
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'¥ '+Math.round(n).toLocaleString('zh-CN');
const kg=n=>Number(n||0).toFixed(1);
let storageOK=true,legacy=false,hadCorrupt=false;
function readProfile(){try{legacy=!!localStorage.getItem('mi-v01');const raw=localStorage.getItem(E.SAVE_KEY);if(!raw)return E.freshProfile();const parsed=E.parseSave(raw);if(parsed)return parsed;hadCorrupt=true;localStorage.setItem(E.SAVE_KEY+'-unreadable-backup',raw);return E.freshProfile();}catch{storageOK=false;return E.freshProfile();}}
let profile=readProfile(),view='map',tab='衣服',selectedRegion='africa',selectedRouteId=ROUTES[0].id,selectedContact=null,selectedRecord=null,toastTimer;
const run=()=>profile.run,route=()=>routeById[run()?.routeId]||ROUTES[0],active=()=>run()&&run().stage!=='ending';
function save(){try{localStorage.setItem(E.SAVE_KEY,JSON.stringify(profile));storageOK=true;}catch{storageOK=false;}updateSaveStatus();}
function updateSaveStatus(){const status=$('#save-status');status.textContent=storageOK?'旅行会自动保存':'暂时无法存档 · 请勿关闭本页';status.className=storageOK?'':'save-error';}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2600);}
function btn(label,action,extra='',kind='primary'){return `<button class="btn ${kind}" data-action="${action}" ${extra}>${label}<span aria-hidden="true">↗</span></button>`;}
function sceneHTML(type,label,small=''){return `<div class="scene-frame"><canvas data-scene="${type}" role="img" aria-label="${esc(label)}的像素旅行场景"></canvas><span class="scene-label">${esc(label)}</span><span class="scene-bottom">${esc(small)}</span></div>`;}
function openModal(title,body,actions=''){modal.innerHTML=`<div class="modal-head"><h2 id="modal-title">${title}</h2><button data-action="close" class="close-btn" aria-label="关闭">×</button></div><div class="modal-body">${body}</div>${actions?`<div class="modal-actions">${actions}</div>`:''}`;if(!modal.open)modal.showModal();drawCanvases();}
function closeModal(){modal.close();}
function render({scroll=true}={}){
 for(const b of document.querySelectorAll('nav button'))b.classList.toggle('active',b.dataset.action===view);
 if(view==='play'&&!run())view='map';
 if(view==='map')renderMap();else if(view==='play')renderPlay();else if(view==='journal')renderJournal();else if(view==='phone')renderPhone();else if(view==='records')renderRecords();else if(view==='record')renderEnding(selectedRecord);else renderMap();
 drawCanvases();updateSaveStatus();
 if(scroll){window.scrollTo({top:0,behavior:'instant'});app.focus({preventScroll:true});}
}
function drawCanvases(){document.querySelectorAll('canvas[data-scene]').forEach(c=>scene(c,c.dataset.scene,c.dataset.recordOutfit?JSON.parse(c.dataset.recordOutfit):run()?.outfit||{}));document.querySelectorAll('canvas[data-avatar]').forEach(c=>avatar(c,run()?.outfit||{}));if($('#world-map'))drawMap($('#world-map'));}
const regions=[{id:'north',name:'北美洲',en:'N. AMERICA',x:24,y:33},{id:'south',name:'南美洲',en:'S. AMERICA',x:34,y:62},{id:'europe',name:'欧洲',en:'EUROPE',x:53,y:28},{id:'asia',name:'亚洲',en:'ASIA',x:74,y:33},{id:'africa',name:'非洲',en:'AFRICA',x:54,y:57},{id:'oceania',name:'大洋洲',en:'OCEANIA',x:83,y:69},{id:'antarctica',name:'南极洲',en:'ANTARCTICA',x:52,y:86}];
function renderMap(){
 const matchingRoutes=ROUTES.filter(r=>r.region===selectedRegion);const r=matchingRoutes.find(r=>r.id===selectedRouteId)||matchingRoutes[0]||ROUTES[0];if(matchingRoutes.length)selectedRouteId=r.id;const count=profile.records.filter(x=>x.routeId===r.id).length,region=regions.find(x=>x.id===selectedRegion)||regions[4];
 const regionCard=matchingRoutes.length?`<div class="kicker">FIELD ROUTE / ${esc(r.number)}</div><h2>${esc(r.name)}<br><small>${r.days} DAYS</small></h2><div class="route-meta"><span>${esc(r.coordinates||r.label)}</span><span>FIELD RECORD × ${count}</span></div><p class="route-description">${esc(r.coverText||r.intro).replace(/\n/g,'<br>')}</p>${matchingRoutes.length>1?`<div class="route-options">${matchingRoutes.map(rt=>`<button class="outfit-btn ${rt.id===r.id?'active':''}" data-action="select-route" data-route="${rt.id}">ROUTE ${rt.number}</button>`).join('')}</div>`:''}${btn(active()&&run().routeId===r.id?'继续这次旅行':'打开这条路线',active()&&run().routeId===r.id?'continue':'start')}<p class="micro">${esc(r.edition||r.label)}<br>${esc(r.playTime||'')} · 不同选择，不同记录</p>`:`<div class="kicker">EARTH / ${esc(region.en)}</div><h2 style="font-size:33px">${esc(region.name)}</h2><div class="route-meta"><span>NO FIELD RECORD</span></div><p class="route-description">这里一直在地图上。<br>米的旅行还没有写到这一页。</p>${btn('看看非洲的那一页','region','data-region="africa"')}<p class="micro">地图上没有需要被填满的进度。</p>`;
 app.innerHTML=`<section class="world"><div class="world-heading"><div><p class="kicker">EARTH / 001 — FIELD RECORDS</p><h1>世界很大，先出门吧。</h1><p class="subtitle">米的旅行，一次一条路线。</p></div><div class="coordinates">CURRENT PLANET: EARTH<br>THE MAP IS ALWAYS INCOMPLETE</div></div><div class="world-layout"><div class="map-panel"><div class="map-head"><span>MI’S WORLD ATLAS</span><span>一张还没有画完的地图</span></div><div class="map-view"><canvas id="world-map" role="img" aria-label="完整世界地图：七大洲都在，非洲有一条旅行路线，其他地区尚无旅行记录"></canvas>${regions.map(x=>`<button class="region ${x.id===selectedRegion?'selected':''}" style="left:${x.x}%;top:${x.y}%" data-action="region" data-region="${x.id}" aria-label="${x.name}，${ROUTES.some(rt=>rt.region===x.id)?'FIELD RECORD '+profile.records.filter(rec=>routeById[rec.routeId]?.region===x.id).length+' 次':'NO FIELD RECORD'}">${x.en}<span>${ROUTES.some(rt=>rt.region===x.id)?'FIELD RECORD × '+profile.records.filter(rec=>routeById[rec.routeId]?.region===x.id).length:'NO FIELD RECORD'}</span></button>`).join('')}</div><div class="map-legend"><span><i class="legend-dot"></i>现实中的旅行路线</span><span><i class="legend-dot unrecorded"></i>尚无旅行记录</span></div></div><aside class="route-card">${regionCard}</aside></div><div class="world-bottom"><p class="world-note"><span class="asterisk">✳</span>一次旅行，不能代表一个地方。</p><button class="text-btn" data-action="records">归来记录 ${String(profile.records.length).padStart(2,'0')} ↗</button></div>${routePreview(r)}${legacy?'<p class="micro" style="margin-top:18px">你的早期试玩还在。<a href="legacy/">打开旧版与旧存档 ↗</a></p>':''}</section>`;
}
function routePreview(r){return `<section class="route-preview"><header><p class="kicker">ROUTE ${r.number} / AFRICA</p><p class="micro">沿真实行程排列 · 后续站点先夹上书签</p></header><div class="stops">${r.stops.map((s,i)=>`<div class="stop ${s.available?'available':''}"><b>${esc(s.name)}</b><small>${s.days} / ${s.en}</small><em>${s.available?'本版旅行页':'书签 · 待续'}</em></div>`).join('')}</div></section>`;}
function travelHeader(){const r=run();return `<div class="travel-head"><button class="back" data-action="map">← 世界地图</button><div class="hud"><div><span>剩余旅费</span>${money(r.money)}</div><div><span>托运行李</span>${kg(E.checkedWeight(r))} kg</div></div></div>`;}
function side(){const r=run(),n=E.currentNode(r),day=n?.day||42;const frequent=CONTACTS.filter(c=>profile.contacts[c.id]).sort((a,b)=>profile.contacts[b.id]-profile.contacts[a.id])[0];const thought=frequent&&profile.contacts[frequent.id]>=2?frequent.thought:(r.notes.at(-1)?.text||'每次出门，都会装进一些“万一”。');return `<aside class="story-side"><p class="side-label">ROUTE ${esc(route().number)} / ${esc(route().name)}</p><div class="itinerary">${route().stops.map((s,i)=>`<div class="step ${!s.available?'future':''} ${i===0&&day<13||i===1&&day>=13&&day<18?'current':''}"><strong>${esc(s.name)}</strong><small>${s.available?s.days+' / '+s.theme:'BOOKMARK / 待续'}</small></div>`).join('')}</div><div class="field-note"><p class="kicker">MI’S MARGIN NOTES</p><p>${esc(thought)}</p></div><div class="side-tools">${btn('看看带了什么','wardrobe','','')}${btn('翻开旅行手记','journal','','')}</div></aside>`;}
function shellStory(content){return `<section class="travel">${travelHeader()}<div class="travel-layout"><div class="story">${content}</div>${side()}</div></section>`;}
function renderPlay(){
 const r=run();
 if(r.stage==='reason'){app.innerHTML=shellStory(`${sceneHTML('home','出发前一天 / 米的房间','BEFORE DEPARTURE')}<div class="story-copy"><p class="kicker">ROUTE 001 / A SMALL QUESTION</p><h1>米为什么要出去旅行？</h1><p class="prose">行李箱打开了。\n这个问题倒是没有提前准备。</p></div><div class="choices">${['想看没见过的东西。','一直想去。','不知道。','票都买了。'].map((x,i)=>`<button class="choice" data-action="reason" data-id="${i}"><span class="choice-number">0${i+1}</span><b>${x}</b><span>↗</span></button>`).join('')}</div>`);return;}
 if(r.stage==='packing'||r.stage==='return-pack'){renderPacking(r.stage==='return-pack');return;}
 if(r.stage==='reflect'){renderReflect();return;}
 if(r.stage==='ending'){renderEnding(profile.records.find(x=>x.runId===r.id));return;}
 if(r.stage==='social'||r.stage==='chat'){renderSocial();return;}
 const n=E.currentNode(r);if(!n){r.stage='return-pack';save();renderPacking(true);return;}
 if(r.stage==='result'){
  app.innerHTML=shellStory(`${sceneHTML(n.scene,n.place,`DAY ${String(n.day).padStart(2,'0')} / 42`)}<section class="result-card"><span class="stamp">${esc(r.pending.stamp)}</span><h1>${esc(r.pending.label)}</h1><p class="prose">${esc(r.pending.text)}</p>${r.pending.cost?`<span class="receipt-cost">支出 ${money(r.pending.cost)} · 已记在小票上</span>`:''}</section>${btn(n.social?'拿出手机':'把这一页翻过去','next')}`);return;
 }
 app.innerHTML=shellStory(`${sceneHTML(n.scene,n.place,`DAY ${String(n.day).padStart(2,'0')} / 42`)}<div class="story-copy"><p class="kicker">${n.eyebrow}</p><h1>${esc(E.value(n.title,r))}</h1><p class="prose">${esc(E.value(n.text,r))}</p>${['safari-morning','island-wind'].includes(n.id)&&CONTACTS.some(c=>(profile.contacts[c.id]||0)>=2)?`<p class="margin-thought">「${esc([...CONTACTS].sort((a,b)=>(profile.contacts[b.id]||0)-(profile.contacts[a.id]||0))[0].thought)}」</p>`:''}</div>${n.id==='interlude'?`<div class="bookmarks">${route().stops.filter(s=>!s.available).map(s=>`<div class="bookmark"><span>${s.name}</span><small>${s.theme}</small></div>`).join('')}</div>`:''}<div class="choices">${n.choices.map((c,i)=>{const cost=E.choiceCost(r,c),fee=c.limit?Math.ceil(E.overweightFee(r,c.limit)):0;return `<button class="choice" data-action="choose" data-index="${i}" ${E.canAfford(r,cost)?'':'disabled'}><span class="choice-number">${String(i+1).padStart(2,'0')}</span><span><b>${esc(c.label)}</b>${c.detail||cost?`<small>${esc(c.detail||'')}${fee?' · 含超重费 '+money(fee):''}</small>`:''}</span><span class="price">${cost?money(cost):'↗'}</span></button>`;}).join('')}</div>${n.kind==='booking'?'<p class="micro" style="margin-top:15px">金额为游戏内旅费。每种安排，都有自己的那几天。</p>':''}<button class="text-btn mobile-tools" data-action="wardrobe" style="margin-top:10px">行李与换装 ↗</button>`);
}
function outfitControls(r){const clothes=r.bag.filter(id=>itemById[id]?.slot);return `<div class="wardrobe"><h3>今天穿什么</h3><p class="micro">从带上的衣服里选。衣服仍计入行李。</p>${clothes.length?`<div class="outfit-list">${clothes.map(id=>{const item=itemById[id],on=r.outfit[item.slot]===id;return `<button class="outfit-btn ${on?'active':''}" data-action="equip" data-id="${id}" aria-pressed="${on}">${item.name}${on?' ✓':''}</button>`;}).join('')}</div>`:'<p class="micro">米先穿着出门时的衣服。</p>'}</div>`;}
function renderPacking(returning=false){
 const r=run(),weight=E.checkedWeight(r),over=weight>BAG_LIMIT,fee=Math.ceil(E.overweightFee(r));
 const action=returning?'return-finish':'depart';
 const go=over?(returning?`付 ${money(fee)} 超重费，带回家`:`还需取出 ${kg(weight-BAG_LIMIT)} kg`):returning?'拉上箱子，回家':'关上箱子，出发';
 const inventory=returning?`<div><p class="kicker">带出去的 / 带回来的</p><div class="pack-toolbar"><p class="micro">随身包 ${kg(E.carryWeight(r))} / ${HAND_LIMIT} kg。<br>衣服可穿上，每个部位一件。</p><button class="text-btn" data-action="restore">放回刚才取出的物品</button></div>${r.bag.length?r.bag.map(id=>{const i=itemById[id];return `<div class="inventory-row"><div><strong>${i.name}</strong><small>${kg(i.weight)} kg · ${i.souvenir?'路上带来的':'出发时的东西'}${r.worn.includes(id)?' · 穿在身上':r.carry.includes(id)?' · 随身包':''}</small></div><div class="item-actions"><button data-action="carry" data-id="${id}" class="${r.carry.includes(id)?'active':''}" ${i.carryOnly?'disabled':''}>${r.carry.includes(id)?'放回箱子':'放随身包'}</button>${i.slot?`<button data-action="wear" data-id="${id}" class="${r.worn.includes(id)?'active':''}">${r.worn.includes(id)?'脱下':'穿上'}</button>`:''}<button data-action="discard" data-id="${id}">留下</button></div></div>`;}).join(''):'<p class="empty">箱子空了。还剩空箱自己。</p>'}</div>`:`<div><div class="tabs" role="group" aria-label="物品分类">${['衣服','日用','随身物'].map(t=>`<button data-action="tab" data-tab="${t}" class="${t===tab?'active':''}" aria-pressed="${t===tab}">${t}</button>`).join('')}</div><div class="pack-toolbar"><p class="micro">点一下放进箱子，再点一下取出。</p><button class="text-btn" data-action="preset">先装一套日常行李 ↗</button></div><div class="item-grid">${ITEMS.filter(i=>i.group===tab&&!i.souvenir).map(i=>{const on=r.bag.includes(i.id);return `<button class="item ${on?'selected':''}" data-action="item" data-id="${i.id}" aria-pressed="${on}" aria-label="${i.name}，${kg(i.weight)}千克，${on?'已带上':'未带上'}"><b>${i.name}</b><span class="item-weight">${kg(i.weight)} kg</span><span class="item-note">${i.note}</span><span class="check" aria-hidden="true">${on?'✓':''}</span></button>`;}).join('')}</div></div>`;
 app.innerHTML=`<section class="packing">${travelHeader()}<div class="pack-heading"><p class="kicker">${returning?'RETURN / PACKING AGAIN':'42 DAYS / BEFORE DEPARTURE'}</p><h1>${returning?'什么跟米一起回家？':'42天。米打开了行李箱。'}</h1><p class="prose">${returning?'箱子还是那个箱子。里面已经不全是原来的东西。':`还剩 ${kg(Math.max(0,BAG_LIMIT-weight))} kg。\n“万一用得上”，好像什么都能带。`}</p></div><div class="pack-layout"><aside class="pack-summary ${over?'over':''}"><div class="avatar-row"><canvas data-avatar role="img" aria-label="米当前的像素穿搭"></canvas><p class="avatar-label">米 / MI<small>READY, MAYBE.</small></p></div><p class="weight-display">${kg(weight)} <small>/ 20 kg</small></p><div class="weight-bar"><i style="width:${weight/BAG_LIMIT*100}%"></i></div><p class="weight-caption"><b>${over?'超出 '+kg(weight-BAG_LIMIT)+' kg':'托运行李还剩 '+kg(BAG_LIMIT-weight)+' kg'}</b><br>空箱 1.4 kg · 随身包 ${kg(E.carryWeight(r))} kg<br>${returning?`出发总重 ${kg(r.departureWeight)} kg · 现在 ${kg(E.totalWeight(r))} kg`:'充电宝随身带，不放托运行李。'}</p>${btn(go,action,over&&(!returning||!E.canAfford(r,fee))?'disabled':'')}<p class="micro">${over?'也可以取出一些东西，再试着关箱子。':returning?'带回家什么，不必解释得很清楚。':'不用准备好一切，才能出发。'}</p>${returning?'':outfitControls(r)}</aside>${inventory}</div></section>`;
}
function renderSocial(){const r=run(),n=E.currentNode(r);if(r.stage==='chat'){
 const chat=r.messages.at(-1),c=CONTACTS.find(x=>x.id===chat.contact);app.innerHTML=`<section class="phone-page travel">${travelHeader()}<div class="phone-box"><div class="phone-top"><span>${esc(c.name)}</span><span>DAY ${n.day} / MESSAGES</span></div><div class="chat-thread">${chat.lines.map(l=>`<div class="bubble ${l.from==='mi'?'mi':''}"><span class="chat-speaker">${l.from==='mi'?'米':esc(c.name)}</span>${esc(l.text)}</div>`).join('')}</div>${btn('收起手机','social-done')}</div></section>`;return;
 }
 app.innerHTML=`<section class="phone-page travel">${travelHeader()}<div class="phone-box"><div class="phone-top"><span>MI’S PHONE</span><span>${n.id==='beach'?'14:06':'18:42'} ▰▰▰</span></div><h1 class="social-quote">${SOCIAL_PROMPT}</h1><p class="micro">同一件事，突然有了不同的收件人。</p><div class="contact-list">${CONTACTS.map(c=>contactButton(c,'send')).join('')}</div>${btn('这次不发，自己留着','social-skip','','')}</div></section>`;
}
function contactButton(c,action){return `<button class="contact" data-action="${action}" data-contact="${c.id}"><span class="contact-avatar" style="background:${c.color}">${c.mark}</span><span><b>${esc(c.name)}</b><small>${esc(c.detail)}</small></span><span class="arrow">↗</span></button>`;}
function renderReflect(){const r=run();app.innerHTML=shellStory(`${sceneHTML('home','家 / 还是这个房间','AFTER 42 DAYS')}<div class="story-copy"><p class="kicker">THE SAME QUESTION / AGAIN</p><h1>所以，米为什么出去旅行？</h1><p class="prose">箱子摊在地上。\n这次想到的答案，跟出门前不太一样。</p></div><div class="choices">${returnQuestions(r).map((q,i)=>`<button class="choice" data-action="finish" data-ending="${q.id}"><span class="choice-number">${String(i+1).padStart(2,'0')}</span><b>${esc(q.text)}</b><span>↗</span></button>`).join('')}</div>`);}
function renderEnding(record){if(!record){view='map';renderMap();return;}const ending=ENDINGS.find(e=>e.id===record.endingId)||ENDINGS.find(e=>e.id==='next');app.innerHTML=`<section class="ending"><div class="return-paper"><p class="kicker">ROUTE ${esc(routeById[record.routeId]?.number)} / RETURN RECORD ${String(record.number).padStart(2,'0')}</p><h1>${esc(ending.title)}</h1><p class="prose">${esc(ending.text)}</p><div class="return-scene"><canvas data-scene="home" data-record-outfit="${esc(JSON.stringify(record.outfit||{}))}" role="img" aria-label="回到家中的米，行李箱仍然打开着"></canvas></div><div class="return-qa"><small>出门前，米说</small>${esc(record.reason)}</div><div class="return-qa"><small>回家以后，米说</small>${esc(record.returnReason)}</div><div class="return-stats"><div><span>带出去 → 带回来</span><b>${kg(record.departureWeight)} → ${kg(record.returnWeight)} kg</b></div><div><span>还剩的旅费</span><b>${money(record.money)}</b></div></div><p class="micro">一次旅行，留下一份记录。<br>地图还在原来的地方。</p></div><div class="ending-actions">${btn('把这一页放回地图','map')}${btn('同一条路线，再走一次','start','','')}${btn('看看这次的旅行手记','record-notes',`data-record="${record.runId}"`,'')}</div></section>`;}
function allMessages(){const messages=[...(profile.messages||[]),...profile.records.flatMap(x=>x.messages||[]),...(run()?.messages||[])];return messages.filter((m,i)=>messages.findIndex(x=>x.id===m.id)===i);}
function renderPhone(){const c=CONTACTS.find(x=>x.id===selectedContact),messages=c?allMessages().filter(m=>m.contact===c.id):[];app.innerHTML=`<section class="archive"><button class="back-link" data-action="${active()?'continue':'map'}">← ${active()?'回到旅行':'回到地图'}</button><p class="kicker">MI’S PHONE / LONG-TIME FRIENDS</p><h1>${c?esc(c.name):'有空再聊。'}</h1><div class="phone-box">${c?`<button class="text-btn" data-action="contacts">← 所有联系人</button>${messages.length?messages.map(m=>`<div class="phone-top" style="margin-top:20px"><span>DAY ${m.day}</span><span>旧消息还在这里</span></div><div class="chat-thread">${m.lines.map(l=>`<div class="bubble ${l.from==='mi'?'mi':''}"><span class="chat-speaker">${l.from==='mi'?'米':esc(c.name)}</span>${esc(l.text)}</div>`).join('')}</div>`).join(''):'<p class="empty">聊天框还空着。<br>没什么要说的时候，也不必说。</p>'}`:`<p class="micro">没有消息要补交。想起谁，再打开谁。</p><div class="contact-list">${CONTACTS.map(c=>contactButton(c,'contact')).join('')}</div>`}</div></section>`;}
let journalRecord=null;
function renderJournal(){const source=journalRecord||run()||profile.records.at(-1);const notes=source?.notes||[];app.innerHTML=`<section class="archive"><button class="back-link" data-action="${active()?'continue':'map'}">← ${active()?'回到旅行':'回到地图'}</button><p class="kicker">MI’S NOTEBOOK / FIELD NOTES</p><h1>只是米看到的那一点。</h1><div class="journal-list">${notes.length?notes.map(n=>`<article class="journal-entry"><p class="kicker">DAY ${String(n.day).padStart(2,'0')} / ${esc(n.place)}</p><p class="prose">${esc(n.text)}</p></article>`).join(''):'<p class="empty">这一页还没写。<br>先出去，看看再说。</p>'}</div></section>`;}
function renderRecords(){app.innerHTML=`<section class="archive"><button class="back-link" data-action="map">← 回到地图</button><p class="kicker">RETURN RECORDS / A SMALL ARCHIVE</p><h1>回来以后，剩下什么。</h1>${profile.records.length?`<div class="record-list">${[...profile.records].reverse().map(r=>{const e=ENDINGS.find(e=>e.id===r.endingId);return `<button class="record-tile" data-action="record" data-record="${r.runId}"><span class="kicker">${esc(routeById[r.routeId]?.name)} / RECORD ${String(r.number).padStart(2,'0')}</span><h2>${esc(e?.title||'一份归来记录')}</h2><span class="micro">${kg(r.departureWeight)} → ${kg(r.returnWeight)} KG / ↗</span></button>`;}).join('')}</div>`:'<p class="empty">箱子还没有从远方回来。<br>这里不用急着填满。</p>'}</section>`;}
function startRun(){profile.run=E.createRun(selectedRouteId);view='play';selectedRecord=null;journalRecord=null;save();closeModal();render();}
function wardrobeModal(){if(!run()){toast('先打开一条旅行路线。');return;}openModal('行李里的米',`<div class="avatar-row"><canvas data-avatar role="img" aria-label="米当前的穿搭"></canvas><p class="micro">托运行李 ${kg(E.checkedWeight(run()))} kg<br>随身包 ${kg(E.carryWeight(run()))} kg<br>旅费 ${money(run().money)}</p></div>${outfitControls(run())}<p class="micro" style="margin-top:20px">${run().bag.map(id=>esc(itemById[id].name)).join(' · ')||'行李箱还是空的。'}</p>`);}
function menu(){openModal('旅行菜单',`<p>可以把地图放下，过会儿再回来。</p><p class="micro" style="margin-top:12px">${storageOK?'旅程自动保存在这个浏览器里。':'当前无法写入存档，请先保持本页打开。'}<br>归来记录会一直留着。</p>`,` ${active()?btn('继续这次旅行','continue'):''}${btn('世界地图','map','','')}${btn('旅行手记','journal','','')}${btn('归来记录','records','','')}${run()?btn('重新开始这一周目','restart','',''):''}<a class="text-btn" href="legacy/">早期五天试玩与旧存档 ↗</a><p class="micro">v0.2.0 · 纯静态旅行档案</p>`);}
function restoreModal(){const r=run();if(!r.removed.length){toast('还没有取出任何东西。');return;}openModal('还在箱子旁边',`<p class="micro">最后关箱之前，随时可以放回去。</p><div class="contact-list">${r.removed.map(id=>`<button class="contact" data-action="restore-item" data-id="${id}"><b>${itemById[id].name}</b><span class="arrow">${kg(itemById[id].weight)} kg ＋</span></button>`).join('')}</div>`);}
function dispatch(action,b){
 const r=run();
 if(['map','journal','phone','records'].includes(action)){closeModal();view=action;if(action==='journal')journalRecord=null;if(action==='phone')selectedContact=null;render();return;}
 if(action==='continue'){closeModal();view='play';render();return;}
 if(action==='close'){closeModal();return;}if(action==='menu'){menu();return;}
 if(action==='region'){selectedRegion=b.dataset.region;render({scroll:false});return;}
 if(action==='select-route'){selectedRouteId=b.dataset.route;render({scroll:false});return;}
 if(action==='start'||action==='restart'){
  if(active()){openModal('重新打包这一次？','这次还没结束的旅行会重新开始。已经收好的 RETURN RECORD 和旧聊天都会保留。',btn('重新开始这一周目','confirm-start')+btn('继续原来的旅行','continue','',''));}else startRun();return;
 }
 if(action==='confirm-start'){startRun();return;}
 if(action==='record'){selectedRecord=profile.records.find(x=>x.runId===b.dataset.record);view='record';render();return;}
 if(action==='record-notes'){journalRecord=profile.records.find(x=>x.runId===b.dataset.record);view='journal';render();return;}
 if(action==='contact'){selectedContact=b.dataset.contact;render();return;}
 if(action==='contacts'){selectedContact=null;render();return;}
 if(action==='wardrobe'){wardrobeModal();return;}
 if(!r)return;
 if(action==='reason'&&r.stage==='reason'){r.reason=['想看没见过的东西。','一直想去。','不知道。','票都买了。'][Number(b.dataset.id)];r.stage='packing';save();render();return;}
 if(action==='tab'){tab=b.dataset.tab;render({scroll:false});return;}
 if(action==='item'&&r.stage==='packing'){E.toggleItem(r,b.dataset.id);save();render({scroll:false});return;}
 if(action==='preset'&&r.stage==='packing'){E.preset(r);save();render({scroll:false});toast('先装好了这些。随时可以取出来。');return;}
 if(action==='equip'){const i=itemById[b.dataset.id];if(i&&E.equip(r,i.slot,i.id)){save();if(modal.open)wardrobeModal();else render({scroll:false});}return;}
 if(action==='depart'&&r.stage==='packing'){if(E.depart(r)){save();render();}else toast('出发托运上限 20 kg，再拿出一点东西吧。');return;}
 if(action==='choose'){if(E.choose(r,Number(b.dataset.index))){save();render();}return;}
 if(action==='next'){E.afterResult(r);save();render();return;}
 if(action==='send'){if(E.sendMessage(profile,b.dataset.contact)){save();render();}return;}
 if((action==='social-skip'&&r.stage==='social')||(action==='social-done'&&r.stage==='chat')){E.advance(r);save();render();return;}
 if(r.stage==='return-pack'){
  if(action==='carry'||action==='wear'){if(!E.relocate(r,b.dataset.id,action==='carry'?'carry':'worn'))toast('随身包最多 7 kg，先腾一点位置。');save();render({scroll:false});return;}
  if(action==='discard'){E.removeItem(r,b.dataset.id,true);save();render({scroll:false});return;}
  if(action==='restore'){restoreModal();return;}
  if(action==='restore-item'){E.addItem(r,b.dataset.id);r.removed=r.removed.filter(x=>x!==b.dataset.id);save();closeModal();render({scroll:false});return;}
  if(action==='return-finish'){if(E.beginReflection(r,true)){save();render();}else toast('旅费不够，再整理一下箱子吧。');return;}
 }
 if(action==='finish'&&r.stage==='reflect'){const rec=E.finish(profile,b.dataset.ending);if(rec){save();render();}return;}
}
document.addEventListener('click',event=>{const b=event.target.closest('[data-action]');if(!b||b.disabled)return;dispatch(b.dataset.action,b);});
document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();closeModal();view='map';render();});
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
// A second tab may have progressed further. Adopt its save instead of overwriting it.
window.addEventListener('storage',event=>{if(event.key!==E.SAVE_KEY||!event.newValue)return;const incoming=E.parseSave(event.newValue);if(incoming){profile=incoming;closeModal();render({scroll:false});toast('旅行已与另一个窗口同步。');}});
render();
if(hadCorrupt)toast('旧存档暂时读不到，已保留备份。可以重新出发。');
if(!storageOK)toast('浏览器暂时不能存档，旅行仍可继续。');
