import assert from 'node:assert/strict';
const {chromium,webkit}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const state=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('mi-v02')).run);
async function enter(p){await p.goto(process.env.MI_TEST_URL||'http://127.0.0.1:4173');await p.waitForSelector('.font-ready');for(const a of ['journey','phone','unlock'])await p.locator(`[data-action=${a}]`).click();await p.locator('.route-pin.ready').click();await p.locator('[data-action=reason]').first().click();}
for(const [name,engine]of Object.entries({chromium,webkit})){
 const b=await engine.launch(),p=await b.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await enter(p);
 const item=await p.locator('[data-pack-id=tee] canvas').boundingBox(),stage=await p.locator('.packing-stage').boundingBox();await p.mouse.move(item.x+item.width/2,item.y+item.height/2);await p.mouse.down();await p.mouse.move(stage.x+stage.width*.72,stage.y+stage.height*.38,{steps:8});assert.match(await p.locator('.packing-info').innerText(),/白色短袖/);assert.deepEqual((await state(p)).bag,[]);await p.mouse.up();assert.match(await p.locator('.packing-info').innerText(),/白色短袖/);
 await p.locator('[data-pack-id=stripe]').click();assert.equal(await p.locator('.packing-floor > .packing-info').count(),1);assert.doesNotMatch(await p.locator('.packing-info').innerText(),/kg/);assert.equal(await p.locator('.packing-scale').count(),0);
 const panel=await p.locator('.packing-info').evaluate(e=>({color:getComputedStyle(e).backgroundColor,position:getComputedStyle(e).position}));assert.equal(panel.position,'absolute');assert.match(panel.color,/rgba/);

 const floorBefore=await p.locator('.packing-shelf').boundingBox();await p.mouse.click(3,3);assert.equal(await p.locator('.packing-info').isVisible(),false);assert.equal(await p.locator('[aria-pressed=true]').count(),0);assert.deepEqual(await p.locator('.packing-shelf').boundingBox(),floorBefore);await p.locator('[data-pack-id=stripe]').click();assert.equal(await p.locator('.packing-info').isVisible(),true);const initial=await state(p);for(const [width,height]of [[320,568],[375,600],[390,844],[560,1000],[900,600],[1440,1000]]){
  await p.setViewportSize({width,height});const shelfBefore=await p.locator('.packing-shelf').boundingBox();await p.locator('[data-pack-id=stripe]').click();assert.deepEqual(await p.locator('.packing-shelf').boundingBox(),shelfBefore);const info=await p.locator('.packing-info').boundingBox();assert.ok(info.y+info.height<shelfBefore.y);const open=await p.locator('.packing-viewbox').boundingBox();
  await p.locator('.suitcase-zipper').click();assert.equal(await p.locator('.packing-review').count(),1);assert.equal(await p.locator('.packing-floor').getAttribute('inert'),'');assert.equal(await p.locator('[data-pull-handle]').count(),0);assert.equal(await p.locator('.packing-info').isVisible(),false);assert.match(await p.locator('.packing-scale output').innerText(),/1.7/);
  assert.ok((await p.locator('.packing-viewbox').boundingBox()).y>open.y+10);
  const floor=await p.locator('.packing-slot').first().boundingBox();await p.mouse.click(floor.x+floor.width/2,floor.y+floor.height/2);assert.deepEqual((await state(p)).bag,initial.bag);assert.equal(await p.locator('.packing-info').isVisible(),false);
  assert.equal(await p.locator('.packing-scale [data-action=packing-confirm],.packing-scale [data-action=packing-edit]').count(),2);const scale=await p.locator('.packing-weighing').boundingBox();assert.ok(scale.x>=0&&scale.x+scale.width<=width&&scale.y+scale.height<height);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth||document.documentElement.scrollHeight>innerHeight),false);
  if(name==='chromium'&&[320,390].includes(width))await p.screenshot({path:`/tmp/mi-scale-25-${width}.png`});
  const saved=await state(p);await p.reload();assert.deepEqual(await state(p),saved);assert.equal(await p.locator('.packing-review').count(),1);
  await p.locator('[data-action=packing-edit]').click();assert.equal(await p.locator('.packing-scale').count(),0);assert.deepEqual((await state(p)).packingPositions,initial.packingPositions);assert.deepEqual((await state(p)).bag,initial.bag);
  await p.locator('.suitcase-zipper').click();await p.locator('[data-action=packing-confirm]').click();assert.equal(await p.locator('.packing-ready').count(),1);assert.equal(await p.locator('.packing-floor,.packing-scale,.packing-info,.packing-decisions').count(),0);assert.equal(await p.locator('[data-pull-handle]').count(),1);const view=await p.locator('.packing-viewbox').boundingBox();assert.ok(Math.abs(view.y+view.height/2-height/2)<1);
  if(name==='chromium'&&[320,390].includes(width))await p.screenshot({path:`/tmp/mi-ready-25-${width}.png`});
  await p.reload();assert.equal(await p.locator('.packing-ready').count(),1);
  await p.locator('.suitcase-zipper').click();assert.equal(await p.locator('.packing-screen:not(.case-closed)').count(),1);assert.deepEqual((await state(p)).packingPositions,initial.packingPositions);assert.deepEqual((await state(p)).bag,initial.bag);for(let j=0;j<5;j++)await p.locator('.packing-panorama').press('ArrowRight');
 }
 await p.setViewportSize({width:390,height:844});await p.locator('[data-pack-id=stripe]').click();if(name==='chromium')await p.screenshot({path:'/tmp/mi-info-25.png'});assert.deepEqual(errors,[]);await b.close();console.log(`PASS ${name}: floating translucent info and fixed inventory, hidden weights, inert review inventory, back preserves bag/positions, confirmation isolates centered suitcase, save/reload, six sizes`);
}
