import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const {chromium,webkit}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const origin=process.env.MI_TEST_URL||'http://127.0.0.1:4173';
await mkdir('/tmp/mi-packing-free',{recursive:true});
const state=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('mi-v02')).run);
const camera=p=>p.locator('.packing-panorama').evaluate(e=>{const range=e.scrollWidth-e.clientWidth;return range>0?e.scrollLeft/range:.5;});
async function enter(p){await p.goto(origin);await p.waitForSelector('.font-ready');for(const a of ['journey','phone','unlock'])await p.locator(`[data-action=${a}]`).click();await p.locator('.route-pin.ready').click();await p.locator('[data-action=reason]').first().click();}
async function fullPull(p){await p.locator('[data-action=packing-confirm]').click();const stage=await p.locator('.packing-stage').boundingBox(),a=await p.locator('[data-pull-handle]').boundingBox();await p.mouse.move(a.x+a.width/2,a.y+26);await p.mouse.down();await p.mouse.move(a.x+a.width/2,a.y+26-stage.width*.16-2,{steps:10});await p.mouse.up();}
async function pan(p,left){const b=await p.locator('.packing-panorama').boundingBox();for(let j=0;j<2;j++){await p.mouse.move(b.x+b.width*(left?.05:.95),b.y+b.height*.025);await p.mouse.down();await p.mouse.move(b.x+b.width*(left?.95:.05),b.y+b.height*.025,{steps:12});await p.mouse.up();}assert.ok(Math.abs(await camera(p)-(left?0:1))<.001);}
async function drag(p,id,x,y,cancel=false){const a=await p.locator(`[data-pack-id="${id}"] canvas`).boundingBox();let target;if(typeof x==='string'){const b=await p.locator(x).boundingBox();target={x:b.x+b.width/2,y:b.y+b.height/2};}else{const b=await p.locator('.packing-stage').boundingBox();target={x:b.x+b.width*x,y:b.y+b.height*y};}await p.mouse.move(a.x+a.width/2,a.y+a.height/2);await p.mouse.down();await p.mouse.move(target.x,target.y,{steps:12});if(cancel)await p.locator(`[data-pack-id="${id}"]`).dispatchEvent('pointercancel',{pointerId:1});await p.mouse.up();}
function position(r,id,x,y){assert.ok(Math.abs(r.packingPositions[id].x-x)<.003);assert.ok(Math.abs(r.packingPositions[id].y-y)<.003);}
async function weight(p,level){await p.evaluate(level=>{const s=JSON.parse(localStorage.getItem('mi-v02')),r=s.run;r.bag=['laundry','airfryer','ricecooker','spare','coat','tee8','lens','tripod','hat'];if(level===19.9){r.bag=r.bag.filter(id=>id!=='hat');r.bag.push('charger');}if(level===25)r.bag.push('towel','wash','guide','toy','sandals','camera','phone','tee');r.carry=[];r.worn=[];r.packingClosed=false;r.packingPositions={};localStorage.setItem('mi-v02',JSON.stringify(s));},level);await p.reload();}
for(const name of ['chromium','webkit']){
 const b=await ({chromium,webkit})[name].launch(),p=await b.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'}),errors=[],images=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.resourceType()==='image')images.push(r.url());});await enter(p);
 assert.equal((await p.locator('.packing-screen').innerText()).replace(/\s/g,''),'');assert.equal(await p.locator('.packing-scale').count(),0);assert.equal(await p.locator('.packing-heading,.packing-footer,.packing-tabs,[data-action=preset]').count(),0);assert.equal(await p.locator('.packing-stage .packing-slot,.packing-well').count(),0);await p.screenshot({path:`/tmp/mi-packing-free/${name}-empty-right.png`});
 await p.locator('[data-pack-id=tee]').click();assert.deepEqual((await state(p)).bag,[]);assert.match(await p.locator('.packing-info').innerText(),/白色短袖/);assert.match(await p.locator('.packing-info').innerText(),/洗完，第二天还穿。/);assert.doesNotMatch(await p.locator('.packing-info').innerText(),/kg/);
 await drag(p,'tee',.71,.35);assert.deepEqual((await state(p)).bag,['tee']);position(await state(p),'tee',.71,.35);assert.equal(await p.locator('.packing-scale').count(),0);
 await p.locator('[data-pack-id=tee]').click();assert.deepEqual((await state(p)).bag,['tee']);
 await drag(p,'stripe',.8,.5,true);assert.deepEqual((await state(p)).bag,['tee']);assert.equal(await p.locator('.packing-ghost').count(),0);
 await drag(p,'tee',.8187,.6234);position(await state(p),'tee',.8187,.6234);assert.equal(await p.locator('.packing-scale').count(),0);
 await drag(p,'stripe',.8187,.6234);position(await state(p),'stripe',.8187,.6234);position(await state(p),'tee',.8187,.6234);assert.equal((await state(p)).bag.length,2);
 await drag(p,'stripe','.packing-shelf');assert.deepEqual((await state(p)).bag,['tee']);assert.equal((await state(p)).packingPositions.stripe,undefined);
 const held=await p.locator('[data-pack-id=tee] canvas').boundingBox(),viewport=await p.locator('.packing-panorama').boundingBox();await p.mouse.move(held.x+held.width/2,held.y+held.height/2);await p.mouse.down();await p.mouse.move(viewport.x+Math.min(64,viewport.width*.18)*.92,viewport.y+viewport.height*.35,{steps:12});await p.waitForTimeout(1300);assert.equal(await camera(p),0);const cross=await p.locator('.packing-stage').boundingBox();await p.mouse.move(cross.x+cross.width*.25,cross.y+cross.height*.35,{steps:8});await p.mouse.up();assert.deepEqual((await state(p)).bag,['tee']);assert.ok((await state(p)).packingPositions.tee.x<.4,'held item can cross to the other half');
 await pan(p,true);assert.equal((await state(p)).packingClosed,false);await p.screenshot({path:`/tmp/mi-packing-free/${name}-empty-left.png`});
 await drag(p,'stripe',.27,.4);position(await state(p),'stripe',.27,.4);await drag(p,'stripe','.packing-shelf');assert.deepEqual((await state(p)).bag,['tee']);
 await drag(p,'powerbank',.25,.4);assert.deepEqual((await state(p)).carry,['powerbank']);assert.equal(await p.locator('.packing-carry [data-pack-id=powerbank]').count(),1);assert.equal(await p.locator('.packing-carry').isVisible(),true);assert.ok((await p.locator('.packing-carry').boundingBox()).y+(await p.locator('.packing-carry').boundingBox()).height<(await p.locator('.packing-info').boundingBox()).y,'carry item stays above the information panel');
 const ids=await p.locator('[data-pack-id]').evaluateAll(es=>es.map(e=>e.dataset.packId));assert.equal(ids.length,new Set(ids).size);
 await p.locator('.packing-shelf').evaluate(e=>e.scrollTop=150);const scroll=await p.locator('.packing-shelf').evaluate(e=>e.scrollTop);await p.locator('.packing-phone').click();await p.locator('[data-action=unlock]').click();await p.locator('[data-action=close-phone]').click();assert.equal(await p.locator('.packing-shelf').evaluate(e=>e.scrollTop),scroll);assert.equal(await camera(p),0);
 await p.locator('.packing-map').click();assert.equal(await p.locator('#phone-africa-map').count(),1);await p.locator('[data-action=close-phone]').click();const saved=await state(p);await p.reload();assert.deepEqual(await state(p),saved);await pan(p,false);
 for(const [width,height]of [[320,568],[375,600],[390,844],[560,1000],[900,600],[1440,1000]]){
  await p.setViewportSize({width,height});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth||document.documentElement.scrollHeight>innerHeight||scrollY!==0),false);
  const view=await p.locator('.packing-panorama').boundingBox(),stage=await p.locator('.packing-stage').boundingBox();assert.ok(Math.abs(view.width-width)<.01,'camera reaches both screen edges');assert.equal(await p.locator('.packing-panorama').evaluate(e=>getComputedStyle(e).overflowX),'auto');assert.equal(await p.locator('.packing-stage').evaluate(e=>getComputedStyle(e).transform),'none');assert.ok(Math.abs(stage.width/stage.height-400/286)<.01);assert.ok(view.height>height*.4&&view.height<height*.7,'case retains its former large height');assert.ok(await p.locator('.packing-shelf').evaluate(e=>e.clientHeight)>60);
  const slot=await p.locator('.packing-slot').first().evaluate(e=>({border:getComputedStyle(e).borderWidth,shadow:getComputedStyle(e).boxShadow}));assert.equal(slot.border,'0px');assert.match(slot.shadow,/inset/);await p.screenshot({path:`/tmp/mi-packing-free/${name}-${width}.png`});
 }
 for(const [level,tone]of [[19.9,'normal'],[20,'warning'],[25,'danger']]){await weight(p,level);await p.locator('.suitcase-zipper').click();assert.equal(await p.locator('.packing-scale').getAttribute('class'),`packing-scale ${tone}`);assert.equal(await p.locator('.packing-scale output').innerText(),`${level.toFixed(1)}\nkg`);const pixel=await p.locator('[data-scale]').evaluate(c=>Array.from(c.getContext('2d').getImageData(128,64,1,1).data));assert.deepEqual(pixel,tone==='danger'?[189,118,94,255]:tone==='warning'?[223,189,101,255]:[147,153,108,255]);await p.locator('[data-action=packing-edit]').click();}
 await p.locator('.suitcase-zipper').click();assert.equal(await p.locator('[data-action=packing-confirm]').isDisabled(),true);assert.equal(await p.locator('[data-pull-handle]').count(),0);const closed=await state(p);await p.reload();assert.deepEqual(await state(p),closed);await p.locator('[data-action=packing-edit]').click();await weight(p,19.9);await p.locator('.suitcase-zipper').click();await fullPull(p);assert.equal((await state(p)).stage,'event');await p.locator('[data-action=choose]').first().click();await p.locator('[data-action=next]').click();assert.equal(await p.locator('.play-screen').count(),1);
 assert.deepEqual(errors,[]);assert.deepEqual(images,[]);await b.close();console.log(`PASS ${name}: empty case art, large panorama, free placement/overlap/movement/removal/cancel, save, phone/map, six sizes, 20/25kg colors, zipper and story`);
}
const b=await chromium.launch(),ctx=await b.newContext({viewport:{width:320,height:568},isMobile:true,hasTouch:true}),p=await ctx.newPage();await enter(p);const cdp=await ctx.newCDPSession(p);
async function touch(x,y,dx,dy,cancel=false){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=15;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+dx*i/15,y:y+dy*i/15}]});await p.waitForTimeout(20);}await cdp.send('Input.dispatchTouchEvent',{type:cancel?'touchCancel':'touchEnd',touchPoints:[]});await p.waitForTimeout(100);}
const tapItem=await p.locator('[data-pack-id=linen] canvas').boundingBox();await p.touchscreen.tap(tapItem.x+tapItem.width/2,tapItem.y+tapItem.height/2);assert.deepEqual((await state(p)).bag,[]);assert.match(await p.locator('.packing-info').innerText(),/皱了也算一种穿法。/);
let a=await p.locator('[data-pack-id=tee] canvas').boundingBox(),t=await p.locator('.packing-stage').boundingBox();await touch(a.x+a.width/2,a.y+a.height/2,t.x+t.width*.71-a.x-a.width/2,t.y+t.height*.35-a.y-a.height/2);assert.deepEqual((await state(p)).bag,['tee']);position(await state(p),'tee',.71,.35);assert.match(await p.locator('.packing-info').innerText(),/白色短袖/);
a=await p.locator('[data-pack-id=stripe] canvas').boundingBox();await touch(a.x+a.width/2,a.y+a.height/2,0,-50,true);assert.deepEqual((await state(p)).bag,['tee']);assert.equal(await p.locator('.packing-ghost').count(),0);assert.match(await p.locator('.packing-info').innerText(),/条纹上衣/);
a=await p.locator('.packing-shelf').boundingBox();await touch(a.x+1,a.y+Math.min(a.height-12,90),0,-75);assert.ok(await p.locator('.packing-shelf').evaluate(e=>e.scrollTop)>20);assert.equal(await p.evaluate(()=>scrollY),0);assert.equal(await p.evaluate(()=>getSelection().toString()),'');
a=await p.locator('.packing-panorama').boundingBox();for(let j=0;j<2;j++)await touch(a.x+a.width*.05,a.y+a.height*.025,a.width*.9,0);assert.equal(await camera(p),0);assert.equal((await state(p)).packingClosed,false);for(let j=0;j<2;j++)await touch(a.x+a.width*.95,a.y+a.height*.025,-a.width*.9,0);assert.equal(await camera(p),1);assert.deepEqual((await state(p)).bag,['tee']);await b.close();console.log('PASS native touch: free placement, cancel, independent scrolling and full-size horizontal camera');
