const {chromium,webkit}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
await fs.mkdir('/tmp/mi-story-review',{recursive:true});
for(const [name,browserType] of [['chromium',chromium],['webkit',webkit]]){
 const browser=await browserType.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});const errors=[],images=[];page.on('request',r=>{if(r.resourceType()==='image')images.push(r.url());});page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.MI_TEST_URL||'http://127.0.0.1:4173');await page.waitForSelector('.font-ready');
 await page.locator('[data-action=journey]').click();await page.locator('[data-action=phone]').click();await page.locator('[data-action=unlock]').click();await page.locator('.route-pin.ready').click();
 await page.screenshot({path:`/tmp/mi-story-review/${name}-home.png`});await page.locator('[data-action=reason]').first().click();await page.locator('[data-action=open-case]').first().click();await page.locator('[data-action=preset]').click();await page.locator('[data-action=depart]').click();
 await page.screenshot({path:`/tmp/mi-story-review/${name}-airport.png`});await page.locator('[data-action=choose]').first().click();await page.locator('[data-action=next]').click();
 assert.equal(await page.locator('[data-scene]').getAttribute('data-story'),'hotel-safari');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 const result=await page.evaluate(async()=>{const {storyScene}=await import('/js/story-art.js');const {africa}=await import('/data/routes/africa-001.js');const hash=c=>{let h=0;for(const x of c.getContext('2d').getImageData(0,0,256,220).data)h=(h*31+x)>>>0;return h;};let animated=0;const hashes=new Set();for(const n of africa.nodes){let c=document.createElement('canvas');storyScene(c,n.scene,{},0,n.id);let a=hash(c);hashes.add(a);storyScene(c,n.scene,{},1,n.id);if(a!==hash(c))animated++;}let c=document.createElement('canvas');storyScene(c,'home',{},0);let a=hash(c);storyScene(c,'home',{hat:true,top:'linen',outer:'coat'},0);return {count:africa.nodes.length,animated,distinct:hashes.size,outfit:a!==hash(c)};});assert.equal(result.animated,result.count);assert.equal(result.distinct,result.count);assert.ok(result.outfit);assert.deepEqual(errors,[]);assert.deepEqual(images,[]);console.log(name,result);
 if(name==='chromium'){
 await page.evaluate(async()=>{const {storyScene}=await import('/js/story-art.js');document.body.innerHTML='';document.body.style='margin:0;background:#241e20;display:grid;grid-template-columns:repeat(4,256px);gap:8px;width:1048px';for(const [type,id]of [['home','reason'],['room','kitchen'],['savanna','safari-morning'],['camp','hippo-night'],['desert','tree-sunset'],['falls','falls-walk'],['river','chobe-river'],['river','whale'],['city','sunday'],['cape','cape-sea'],['coach','cold-coach'],['airport','flight-out'],['road','border-bridge'],['busstop','bus-wait'],['room','laundry-day'],['savanna','mountain']]){let div=document.createElement('div'),c=document.createElement('canvas');div.style='color:#ffe3a0;font:12px monospace';div.textContent=type+' / '+id;div.append(c);document.body.append(div);storyScene(c,type,{},0,id);}});await page.setViewportSize({width:1048,height:976});await page.screenshot({path:'/tmp/mi-story-review/all-scenes.png',fullPage:true});}
 await browser.close();
}
