"""Create compact contextual geometry from Natural Earth 1:10m GeoJSON.
Input: land, countries, rivers and lakes from nvkelso/natural-earth-vector.
Usage: python build-context-maps.py /tmp/mi-map
Requires shapely. Only generated map data is shipped, never source datasets.
"""
import json,sys,re
from pathlib import Path
from shapely.geometry import shape,box,mapping
from shapely.ops import unary_union
root=Path(__file__).resolve().parents[1]
prefix=sys.argv[1]
land=unary_union([shape(f['geometry']) for f in json.loads(Path(prefix+'-land.json').read_text())['features']])
lakes=unary_union([shape(f['geometry']) for f in json.loads(Path(prefix+'-lakes.json').read_text())['features'] if f['geometry']])
rivers=unary_union([shape(f['geometry']) for f in json.loads(Path(prefix+'-rivers.json').read_text())['features'] if f['geometry']])
countries=[shape(f['geometry']) for f in json.loads(Path(prefix+'-countries.json').read_text())['features']]
borders=unary_union([c.boundary for c in countries])
locations={k:([float(x) for x in coord.split(',')],float(span)) for k,coord,span in re.findall(r'(\w+):\{coord:\[([^\]]+)\],span:([\d.]+)',(root/'data/geography.js').read_text())}
locations['africa']=([22.5,0],85)
def clean(g,tolerance):
 if g.is_empty:return None
 return mapping(g.simplify(tolerance,preserve_topology=True))
def round_values(v):
 if isinstance(v,float):return round(v,4)
 if isinstance(v,(list,tuple)):return [round_values(x) for x in v]
 if isinstance(v,dict):return {k:round_values(x) for k,x in v.items()}
 return v
result={}
for key,(coord,span) in locations.items():
 lon,lat=coord
 bounds=[lon-span/2,lat-span/2,lon+span/2,lat+span/2]
 if key=='africa':bounds=[-20,-38,65,40]
 b=box(*bounds);tol=span/500
 region_borders=unary_union([c.simplify(.16,preserve_topology=True).boundary for c in countries]) if key=='africa' else borders
 region_rivers=None if key=='africa' else clean(rivers.intersection(b),tol)
 result[key]={'bounds':bounds,'land':clean(land.intersection(b),tol),'water':clean(lakes.intersection(b),tol),'rivers':region_rivers,'borders':clean(region_borders.intersection(b),tol)}
(root/'assets/context-maps.js').write_text('// Natural Earth 1:10m. Public domain. Generated by scripts/build-context-maps.py.\nexport const CONTEXT_MAPS='+json.dumps(round_values(result),separators=(',',':'))+';\n')
print('Generated regions:',len(result),'bytes:',(root/'assets/context-maps.js').stat().st_size)
